# Generated by Django 4.1.6 on 2023-03-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, default='SOME STRING', max_length=255)),
                ('href', models.ImageField(blank=True, null=True, upload_to='images/category/')),
                ('url', models.CharField(blank=True, default='SOME STRING', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='SOME STRING', max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='SOME STRING', max_length=2000, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='В наличии')),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='images/item')),
                ('category_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'verbose_name': 'товары',
            },
        ),
    ]
