# Generated by Django 4.1.5 on 2023-02-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Джинсы', 'Джинсы'), ('Очки', 'Очки'), ('Верхняя одежда', 'Верхняя одежда'), ('Обувь', 'Обувь')], db_index=True, default=False, max_length=255)),
            ],
            options={
                'verbose_name': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='В наличии')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'verbose_name': 'товары',
            },
        ),
    ]
