# Generated by Django 4.1.5 on 2023-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Джинсы', 'Джинсы'), ('Обувь', 'Обувь'), ('Верхняя одежда', 'Верхняя одежда'), ('Очки', 'Очки')], db_index=True, default=False, max_length=255),
        ),
    ]
