# Generated by Django 4.1.5 on 2023-02-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_id_product_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='category_product',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[(1, 'Обувь'), ('Очки', 'Очки'), ('Верхняя одежда', 'Верхняя одежда'), ('Джинсы', 'Джинсы')], db_index=True, default=False, max_length=255),
        ),
    ]
