# Generated by Django 4.1.6 on 2023-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_product_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Очки', 'Очки'), ('Верхняя одежда', 'Верхняя одежда'), (1, 'Обувь'), ('Джинсы', 'Джинсы')], db_index=True, default=False, max_length=255),
        ),
    ]
